[general]
import = [
  "/opt/homebrew/lib/node_modules/alacritty-themes/themes/Google.light.toml"
]

[font]
# size = 14.8
size = 14.4

[font.offset]
x = 0
y = 4

[font.glyph_offset]
x = 0
y = 2

[font.normal]
family = "JetBrains Mono"
# family = "Fira Code"
# style = "Regular"
style = "Medium"

[window]
# decorations = "None"
startup_mode = "Maximized"
# decorations_theme_variant = "Dark"
